/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gabrielamontes_examen1p2;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriela Montes
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CRUD = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tf_direccionip = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tf_mascaradered = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tf_hostname = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tf_tipal = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tf_targraf = new javax.swing.JTextPane();
        agregar_escritorio = new javax.swing.JButton();
        S_capram = new javax.swing.JSpinner();
        s_capal = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tf_direccioniplaptop = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        tf_mascaraderedlaptop = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        tf_hostnamelaptop = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tf_marcalaptop = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        tf_defpanlaptop = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        tf_rgblaptop = new javax.swing.JTextPane();
        agregar_laptop = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_lista = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        b_borrarcrud = new javax.swing.JButton();
        s_pos = new javax.swing.JSpinner();
        Ingresar = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabel6 = new javax.swing.JLabel();
        b_buscarip = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        B_Agregar = new javax.swing.JButton();
        B_Ingresar = new javax.swing.JButton();

        jTabbedPane2.setBackground(new java.awt.Color(239, 239, 253));

        jPanel3.setBackground(new java.awt.Color(238, 238, 253));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Direccion IP");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 55, 129, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Mascara de red");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 92, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Hostname");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 129, 126, -1));

        jScrollPane1.setViewportView(tf_direccionip);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 58, 325, -1));

        jScrollPane2.setViewportView(tf_mascaradered);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 95, 325, -1));

        jScrollPane3.setViewportView(tf_hostname);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 129, 325, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Capacidad almacenamiento");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 205, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Capacidad RAM");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 166, 148, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tipo de almacenamiento");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 241, 174, -1));

        jScrollPane9.setViewportView(tf_tipal);

        jPanel3.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 239, 324, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Tarjeta Grafica");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 279, 132, -1));

        jScrollPane10.setViewportView(tf_targraf);

        jPanel3.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 279, 324, -1));

        agregar_escritorio.setBackground(new java.awt.Color(176, 176, 255));
        agregar_escritorio.setForeground(new java.awt.Color(255, 255, 255));
        agregar_escritorio.setText("Agregar");
        agregar_escritorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_escritorioMouseClicked(evt);
            }
        });
        agregar_escritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_escritorioActionPerformed(evt);
            }
        });
        jPanel3.add(agregar_escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 121, -1));
        jPanel3.add(S_capram, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 170, 325, -1));
        jPanel3.add(s_capal, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 205, 324, -1));

        jTabbedPane2.addTab("Escritorio", jPanel3);

        jPanel6.setBackground(new java.awt.Color(238, 238, 253));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Direccion IP");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 55, 129, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Mascara de red");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 92, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Hostname");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 129, 126, -1));

        jScrollPane11.setViewportView(tf_direccioniplaptop);

        jPanel6.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 58, 325, -1));

        jScrollPane12.setViewportView(tf_mascaraderedlaptop);

        jPanel6.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 95, 325, -1));

        jScrollPane13.setViewportView(tf_hostnamelaptop);

        jPanel6.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 129, 325, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Definicion de Pantalla");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 205, -1, -1));

        jScrollPane14.setViewportView(tf_marcalaptop);

        jPanel6.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 166, 325, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Marca");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 166, 148, -1));

        jScrollPane15.setViewportView(tf_defpanlaptop);

        jPanel6.add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 203, 325, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setText("Tiene teclado RGB?");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 239, 174, -1));

        jScrollPane16.setViewportView(tf_rgblaptop);

        jPanel6.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 237, 324, -1));

        agregar_laptop.setBackground(new java.awt.Color(176, 176, 255));
        agregar_laptop.setForeground(new java.awt.Color(255, 255, 255));
        agregar_laptop.setText("Agregar");
        agregar_laptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregar_laptopMouseClicked(evt);
            }
        });
        agregar_laptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_laptopActionPerformed(evt);
            }
        });
        jPanel6.add(agregar_laptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 121, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Laptop", jPanel4);

        jPanel7.setBackground(new java.awt.Color(220, 239, 220));

        ta_lista.setColumns(20);
        ta_lista.setRows(5);
        jScrollPane5.setViewportView(ta_lista);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Listar", jPanel7);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Ingrese la posición que desea borrar:");

        b_borrarcrud.setText("Borrar");
        b_borrarcrud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_borrarcrudMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(b_borrarcrud)
                .addGap(57, 57, 57))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(s_pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(s_pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(b_borrarcrud)
                .addGap(27, 27, 27))
        );

        jTabbedPane2.addTab("Borrar", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout CRUDLayout = new javax.swing.GroupLayout(CRUD.getContentPane());
        CRUD.getContentPane().setLayout(CRUDLayout);
        CRUDLayout.setHorizontalGroup(
            CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CRUDLayout.setVerticalGroup(
            CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(242, 220, 253));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBackground(new java.awt.Color(234, 225, 243));
        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 320, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Ingresar direccion IP:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        b_buscarip.setBackground(new java.awt.Color(215, 175, 255));
        b_buscarip.setForeground(new java.awt.Color(255, 255, 255));
        b_buscarip.setText("Buscar");
        b_buscarip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_buscaripMouseClicked(evt);
            }
        });
        b_buscarip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buscaripActionPerformed(evt);
            }
        });
        jPanel5.add(b_buscarip, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 323, 90, 30));

        javax.swing.GroupLayout IngresarLayout = new javax.swing.GroupLayout(Ingresar.getContentPane());
        Ingresar.getContentPane().setLayout(IngresarLayout);
        IngresarLayout.setHorizontalGroup(
            IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        IngresarLayout.setVerticalGroup(
            IngresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 51));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(102, 0, 102));
        jTabbedPane1.setForeground(new java.awt.Color(204, 204, 255));

        B_Agregar.setText("Agregar");
        B_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AgregarActionPerformed(evt);
            }
        });
        jTabbedPane1.addTab("tab1", B_Agregar);

        B_Ingresar.setText("Ingresar");
        B_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_IngresarActionPerformed(evt);
            }
        });
        jTabbedPane1.addTab("tab2", B_Ingresar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AgregarActionPerformed
    CRUD.setLocationRelativeTo(this);
    CRUD.setVisible(true);
    }//GEN-LAST:event_B_AgregarActionPerformed

    private void B_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IngresarActionPerformed
     Ingresar.setLocationRelativeTo(this);
    Ingresar.setVisible(true);  
    }//GEN-LAST:event_B_IngresarActionPerformed

    private void agregar_escritorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_escritorioActionPerformed
       
    }//GEN-LAST:event_agregar_escritorioActionPerformed

    private void agregar_laptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_laptopActionPerformed
        
    }//GEN-LAST:event_agregar_laptopActionPerformed

    private void b_buscaripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buscaripActionPerformed
 
    }//GEN-LAST:event_b_buscaripActionPerformed

    private void b_buscaripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_buscaripMouseClicked
        Ingresar.setVisible(false);
       CRUD.setVisible(false);
      this.setVisible(false);
        String b=b_buscarip.getText();
       PC p=new PC();
        for (PC pc : pcs) {
            if (pc.getIP().equals(b)) {
                p=pc;
            }
        }
        System.out.println(p.getHostname()+" #");
    }//GEN-LAST:event_b_buscaripMouseClicked

    private void agregar_escritorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_escritorioMouseClicked
        this.setVisible(false);  
        String ip="",red="",hn="",altipo="";
        int capram=0,capal=0;
        boolean targraf=true;
        ip=tf_direccionip.getText();
        red=tf_mascaradered.getText();
        hn=tf_hostname.getText();
        altipo=tf_tipal.getText();
        capram=Integer.parseInt(S_capram.getValue().toString());
        capal=Integer.parseInt(s_capal.getValue().toString());
        if (tf_targraf.getText()=="Si"||tf_targraf.getText()=="si") {
            targraf=true;
        }else{
            targraf=false;
        }
        Escritorio e=new Escritorio(capram, capal,altipo , targraf, ip, red, hn);
        
        pcs.add(e);
        JOptionPane.showConfirmDialog(this, "Escritorio creado");
        tf_direccionip.setText("");
        tf_mascaradered.setText("");
        tf_hostname.setText("");
        tf_tipal.setText("");
        S_capram.setValue(0);
        s_capal.setValue(0);
        tf_targraf.setText("");
        CRUD.setVisible(false);
         this.setVisible(true); 
    }//GEN-LAST:event_agregar_escritorioMouseClicked

    private void agregar_laptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_laptopMouseClicked
      this.setVisible(false); 
        String ip="",red="",hn="",marca="",defpan="";
        boolean rgb=true;
        ip=tf_direccioniplaptop.getText();
        red=tf_mascaraderedlaptop.getText();
        hn=tf_hostnamelaptop.getText();
       marca=tf_marcalaptop.getText();
       defpan=tf_defpanlaptop.getText();
       
        if (tf_rgblaptop.getText()=="Si"||tf_rgblaptop.getText()=="si") {
           rgb=true;
        }else{
            rgb=false;
        }
        
       Laptop l=new Laptop(marca, defpan,rgb,ip,red,hn);
        
        pcs.add(l);
        JOptionPane.showConfirmDialog(this, "Laptop creada");
        tf_direccioniplaptop.setText("");
        tf_mascaraderedlaptop.setText("");
        tf_hostnamelaptop.setText("");
        tf_marcalaptop.setText("");
        tf_defpanlaptop.setText("");
        tf_rgblaptop.setText("");
        CRUD.setVisible(false);
        this.setVisible(true); 
    }//GEN-LAST:event_agregar_laptopMouseClicked

    private void b_borrarcrudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_borrarcrudMouseClicked
       int pos=Integer.parseInt(s_pos.getValue().toString());
       
    }//GEN-LAST:event_b_borrarcrudMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Agregar;
    private javax.swing.JButton B_Ingresar;
    private javax.swing.JFrame CRUD;
    private javax.swing.JFrame Ingresar;
    private javax.swing.JSpinner S_capram;
    private javax.swing.JButton agregar_escritorio;
    private javax.swing.JButton agregar_laptop;
    private javax.swing.JButton b_borrarcrud;
    private javax.swing.JButton b_buscarip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JSpinner s_capal;
    private javax.swing.JSpinner s_pos;
    private javax.swing.JTextArea ta_lista;
    private javax.swing.JTextPane tf_defpanlaptop;
    private javax.swing.JTextPane tf_direccionip;
    private javax.swing.JTextPane tf_direccioniplaptop;
    private javax.swing.JTextPane tf_hostname;
    private javax.swing.JTextPane tf_hostnamelaptop;
    private javax.swing.JTextPane tf_marcalaptop;
    private javax.swing.JTextPane tf_mascaradered;
    private javax.swing.JTextPane tf_mascaraderedlaptop;
    private javax.swing.JTextPane tf_rgblaptop;
    private javax.swing.JTextPane tf_targraf;
    private javax.swing.JTextPane tf_tipal;
    // End of variables declaration//GEN-END:variables
//ArrayLists
    ArrayList<PC> pcs=new ArrayList();
}
